export const ErrorCodes = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_PATH_TRAVERSAL: 'FILE_PATH_TRAVERSAL',
  TARGET_NOT_DIRECTORY: 'TARGET_NOT_DIRECTORY',
  NAME_CONTAINS_PATH_SEPARATOR: 'NAME_CONTAINS_PATH_SEPARATOR',
  WORK_DIR_NOT_CONFIGURED: 'WORK_DIR_NOT_CONFIGURED',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_NOT_CONFIGURED: 'API_KEY_NOT_CONFIGURED',
  NO_ENABLED_MODEL: 'NO_ENABLED_MODEL',
  WINDOW_NOT_READY: 'WINDOW_NOT_READY',
  INVALID_PATH: 'INVALID_PATH',
  SHELL_EXECUTABLE_REQUIRED: 'SHELL_EXECUTABLE_REQUIRED',
  SHELL_PROCESS_EXIT_CODE: 'SHELL_PROCESS_EXIT_CODE',
  /** IM 远程会话（飞书/微信）未开启 allowRemoteSessions 时拦截 browser */
  BROWSER_REMOTE_DISABLED: 'BROWSER_REMOTE_DISABLED',
  /** @deprecated 使用 BROWSER_REMOTE_DISABLED；保留以兼容旧 tool_result */
  BROWSER_FEISHU_REMOTE_DISABLED: 'BROWSER_FEISHU_REMOTE_DISABLED',
  BROWSER_RATE_LIMIT_REJECTED: 'BROWSER_RATE_LIMIT_REJECTED',
  BROWSER_RATE_LIMIT_WAIT_TIMEOUT: 'BROWSER_RATE_LIMIT_WAIT_TIMEOUT',
  PROJECT_MEMORY_ALREADY_EXISTS: 'PROJECT_MEMORY_ALREADY_EXISTS',
  LLM_EMPTY_RESPONSE: 'LLM_EMPTY_RESPONSE',
  CANNOT_OPEN_TERMINAL: 'CANNOT_OPEN_TERMINAL',
  CANNOT_OPEN_LINK: 'CANNOT_OPEN_LINK',
  REMOTE_SESSION_BUSY: 'REMOTE_SESSION_BUSY',
  REMOTE_PARALLEL_FULL: 'REMOTE_PARALLEL_FULL',
  REMOTE_WORKDIR_SWITCH_BUSY: 'REMOTE_WORKDIR_SWITCH_BUSY',
  REMOTE_SESSION_SWITCH_BUSY: 'REMOTE_SESSION_SWITCH_BUSY'
  ,OUTBOUND_SESSION_NOT_FOUND: 'OUTBOUND_SESSION_NOT_FOUND'
  ,OUTBOUND_SESSION_RUNNING: 'OUTBOUND_SESSION_RUNNING'
  ,OUTBOUND_MAX_PARALLEL_REACHED: 'OUTBOUND_MAX_PARALLEL_REACHED'
  ,OUTBOUND_QUEUE_FULL: 'OUTBOUND_QUEUE_FULL'
  ,OUTBOUND_API_KEY_MISSING: 'OUTBOUND_API_KEY_MISSING'
  ,OUTBOUND_CONTEXT_PRESSURE_80: 'OUTBOUND_CONTEXT_PRESSURE_80'
  ,OUTBOUND_WORKDIR_SWITCH_FAILED: 'OUTBOUND_WORKDIR_SWITCH_FAILED'
  ,SKILL_URL_INVALID: 'SKILL_URL_INVALID'
  ,SKILL_URL_UNSUPPORTED_HOST: 'SKILL_URL_UNSUPPORTED_HOST'
  ,SKILL_REPO_NOT_FOUND: 'SKILL_REPO_NOT_FOUND'
  ,SKILL_NETWORK_FAILED: 'SKILL_NETWORK_FAILED'
  ,SKILL_ARCHIVE_TOO_LARGE: 'SKILL_ARCHIVE_TOO_LARGE'
  ,SKILL_TAR_UNAVAILABLE: 'SKILL_TAR_UNAVAILABLE'
  ,SKILL_PATH_NOT_FOUND: 'SKILL_PATH_NOT_FOUND'
  ,SKILL_NOT_FOUND_IN_REPO: 'SKILL_NOT_FOUND_IN_REPO'
  ,SKILL_NAME_CONFLICT: 'SKILL_NAME_CONFLICT'
  ,SKILL_MD_TOO_LARGE: 'SKILL_MD_TOO_LARGE'
  ,SKILL_DIR_TOO_LARGE: 'SKILL_DIR_TOO_LARGE'
  ,SKILL_FRONT_MATTER_INVALID: 'SKILL_FRONT_MATTER_INVALID'
  ,SKILL_FRONT_MATTER_MISSING: 'SKILL_FRONT_MATTER_MISSING'
  ,SKILL_FIELD_MISSING: 'SKILL_FIELD_MISSING'
  ,SKILL_NAME_INVALID: 'SKILL_NAME_INVALID'
  ,SKILL_DESCRIPTION_EMPTY: 'SKILL_DESCRIPTION_EMPTY'
  ,SKILL_MD_MISSING: 'SKILL_MD_MISSING'
  ,SKILL_MD_UNREADABLE: 'SKILL_MD_UNREADABLE'
  ,SKILL_NO_INSTALLABLE_CANDIDATE: 'SKILL_NO_INSTALLABLE_CANDIDATE'
  ,SKILL_INSTALL_CANCELLED: 'SKILL_INSTALL_CANCELLED'
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

const ERROR_CODE_SET = new Set<string>(Object.values(ErrorCodes))

export function isErrorCode(value: string): value is ErrorCode {
  return ERROR_CODE_SET.has(value)
}

/**
 * 拆分「<CODE>: <说明>」或「<CODE>|<说明>」形态的错误文本；取不到已知错误码返回 null。
 * 分隔符优先级为 | 优先于 :，与 formatUserFacingError 的展示链路同源。
 */
export function splitCodedError(raw: string | undefined | null): { code: ErrorCode; detail: string } | null {
  if (!raw) return null
  const trimmed = raw.trim()
  if (!trimmed) return null
  if (isErrorCode(trimmed)) return { code: trimmed, detail: '' }

  // 分隔符按位置顺序尝试，取第一个「左侧确实是已知错误码」的位置：
  // 详情文本自身含 `|`（如 `SKILL_X: a | b`）或含 `:`（如 `SKILL_X|a: b`）都能正确切分
  const separators = [trimmed.indexOf(':'), trimmed.indexOf('|')]
    .filter((index) => index > 0)
    .sort((a, b) => a - b)
  for (const separator of separators) {
    const code = trimmed.slice(0, separator).trim()
    if (isErrorCode(code)) return { code, detail: trimmed.slice(separator + 1).trim() }
  }
  return null
}

/** 只取错误码；调用方据此判定，不再依赖文案子串匹配 */
export function errorCodeOf(raw: string | undefined | null): ErrorCode | null {
  return splitCodedError(raw)?.code ?? null
}
