export const ErrorCodes = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_PATH_TRAVERSAL: 'FILE_PATH_TRAVERSAL',
  TARGET_NOT_DIRECTORY: 'TARGET_NOT_DIRECTORY',
  NAME_CONTAINS_PATH_SEPARATOR: 'NAME_CONTAINS_PATH_SEPARATOR',
  WORK_DIR_NOT_CONFIGURED: 'WORK_DIR_NOT_CONFIGURED',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_NOT_CONFIGURED: 'API_KEY_NOT_CONFIGURED',
  NO_ENABLED_MODEL: 'NO_ENABLED_MODEL',
  WINDOW_NOT_READY: 'WINDOW_NOT_READY',
  INVALID_PATH: 'INVALID_PATH',
  SHELL_EXECUTABLE_REQUIRED: 'SHELL_EXECUTABLE_REQUIRED',
  SHELL_PROCESS_EXIT_CODE: 'SHELL_PROCESS_EXIT_CODE',
  /** IM 远程会话（飞书/微信）未开启 allowRemoteSessions 时拦截 browser */
  BROWSER_REMOTE_DISABLED: 'BROWSER_REMOTE_DISABLED',
  /** @deprecated 使用 BROWSER_REMOTE_DISABLED；保留以兼容旧 tool_result */
  BROWSER_FEISHU_REMOTE_DISABLED: 'BROWSER_FEISHU_REMOTE_DISABLED',
  BROWSER_RATE_LIMIT_REJECTED: 'BROWSER_RATE_LIMIT_REJECTED',
  BROWSER_RATE_LIMIT_WAIT_TIMEOUT: 'BROWSER_RATE_LIMIT_WAIT_TIMEOUT',
  PROJECT_MEMORY_ALREADY_EXISTS: 'PROJECT_MEMORY_ALREADY_EXISTS',
  LLM_EMPTY_RESPONSE: 'LLM_EMPTY_RESPONSE',
  CANNOT_OPEN_TERMINAL: 'CANNOT_OPEN_TERMINAL',
  CANNOT_OPEN_LINK: 'CANNOT_OPEN_LINK',
  REMOTE_SESSION_BUSY: 'REMOTE_SESSION_BUSY',
  REMOTE_PARALLEL_FULL: 'REMOTE_PARALLEL_FULL',
  REMOTE_WORKDIR_SWITCH_BUSY: 'REMOTE_WORKDIR_SWITCH_BUSY',
  REMOTE_SESSION_SWITCH_BUSY: 'REMOTE_SESSION_SWITCH_BUSY'
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

const ERROR_CODE_SET = new Set<string>(Object.values(ErrorCodes))

export function isErrorCode(value: string): value is ErrorCode {
  return ERROR_CODE_SET.has(value)
}
