export type AgentLogLevel = 'info' | 'warn' | 'error'

export type AgentLogEventName =
  | 'agent.startup'
  | 'llm.request'
  | 'llm.max_tokens_floor'
  | 'llm.response'
  | 'llm.error'
  | 'tool.request'
  | 'tool.confirm'
  | 'tool.error'
  | 'tool.result'
  | 'tool.progress'
  | 'skills.load'
  | 'skills.match'
  | 'skills.route.start'
  | 'skills.route.done'
  | 'skills.route.error'
  | 'skills.invoke'
  | 'projectMemory.loaded'
  | 'projectMemory.loadError'
  | 'projectMemory.watcherError'
  | 'tray.init_ok'
  | 'tray.init_failed'
  | 'browser.action'
  | 'browser.error'
  | 'browser.rate_limit'
  | 'browser.trust.domain'
  | 'trust.remove'
  | 'file.auto_approve'
  | 'file.auto_approve.fallback'
  | 'file.confirm_mode.change'
  | 'shell.security.deny'
  | 'shell.trust.command'
  | 'script.auto_allow.execute'
  | 'shell.path.confirm'
  | 'shell.path.reject'
  | 'shell.precheck'
  | 'shell.confirm'
  | 'shell.exec.start'
  | 'shell.exec.spawned'
  | 'shell.exec.auto_background'
  | 'shell.exec.background'
  | 'shell.exec.finish'
  | 'shell.exec.error'
  | 'workdir.switch.start'
  | 'workdir.switch.done'
  | 'workdir.switch.error'

export type AgentLogFields = Record<string, unknown>
