import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function walkJson(obj: Record<string, unknown>, prefix = ''): string[] {
  const keys: string[] = []
  for (const [k, v] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${k}` : k
    if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
      keys.push(...walkJson(v as Record<string, unknown>, fullKey))
    } else {
      keys.push(fullKey)
    }
  }
  return keys
}

function readNamespaceKeys(langDir: string, namespace: string): string[] {
  const filePath = path.join(langDir, `${namespace}.json`)
  const raw = fs.readFileSync(filePath, 'utf-8')
  const json = JSON.parse(raw) as Record<string, unknown>
  return walkJson(json)
}

const resourcesDir = path.resolve(__dirname, '../src/renderer/i18n/resources')
const sourceLangDir = path.join(resourcesDir, 'zh-CN')
const namespaces = fs
  .readdirSync(sourceLangDir)
  .filter((f) => f.endsWith('.json'))
  .map((f) => path.basename(f, '.json'))

const namespaceKeyEntries = namespaces.map((ns) => {
  const keys = readNamespaceKeys(sourceLangDir, ns)
  const keyUnion = keys.map((k) => `'${k}'`).join(' | ')
  return `  ${ns}: ${keyUnion || 'never'}`
})

const allKeys = namespaces.flatMap((ns) => readNamespaceKeys(sourceLangDir, ns).map((k) => `'${k}'`))

const output = `// Auto-generated by scripts/generate-i18n-types.ts — do not edit manually.

export type I18nNamespaces = ${namespaces.map((n) => `'${n}'`).join(' | ')}

export type I18nKeyPaths = ${allKeys.join(' | ') || 'never'}

export type NamespaceKeyMap = {
${namespaceKeyEntries.join('\n')}
}
`

const outPath = path.resolve(__dirname, '../src/renderer/i18n/types.ts')
fs.writeFileSync(outPath, output, 'utf-8')
console.log(`Generated ${outPath}`)
